server:
  port: 9090

spring:
  aop:
    proxy-target-class: true
    
dubbo:
  application:
      name: system-consumer
  registry:
      address: 192.168.122.191:2181
    
redis:
  host: 192.168.122.175
  port: 8884
  timeout: 3000
  maxidle: 5

service:
  push:
    automatic: http://www.battcn.com/



