server:
  port: 8082
spring:
  application:
    name: battcn-manage
  swagger:
    base-package: com.battcn
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/  
    suffix: .html
mybatis:
  mapper-locations:
  - classpath:com/battcn/mapper/*.xml
  type-aliases-package: com.battcn.model
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity: MYSQL
  mappers:
  - com.battcn.framework.mybatis.mapper.BaseMapper
  not-empty: false
  
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

  