spring:
  application:
    name: battcn-demo-provider
server:
  port: 10020
dubbo:
  scan:
    base-packages: com.battcn.movie.provider.service
  application:
    id: battcn-movie-provider
    name: battcn-movie-provider
    qos-port: 10021
    qos-enable: true
  registry:
    address: N/A
    id: my-registry
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
    status: server
endpoints:
  dubbo:
    enabled: true

