server:
  port: 5001
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: wemirr-platform-tools
  config:
    import:
      - optional:nacos:swagger.yaml # 这是有默认值的写法
      - optional:nacos:${spring.application.name}.properties
      - optional:nacos:mybatis-plus-default.yaml?group=DEFAULT_GROUP&refreshEnabled=true #这是完写法
  cloud:
    nacos:
      discovery:
        metadata:
          group: ${spring.application.name}
          version: 1.0
      config:
        refresh-enabled: true
extend:
  oss:
    cloud:
      qiniu:
        enabled: true
        #access-key: 写自己的
        #secret-key: 写自己的
        region: region0
        bucket: battcn
        mapping-path: http://qiniu.battcn.com