spring:
  datasource:
    #druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wemirr-platform?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: HikariDataSourcePool
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    mongodb:
      database: tenant_form

mybatis-plus:
  mapper-locations:
    - classpath:com/wemirr/**/repository/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wemirr.**.entity;com.wemirr.**.database.mybatis.typehandler
  typeEnumsPackage: com.wemirr.**.enums,com.wemirr.framework.database.mybatis.auth,com.wemirr.framework.database.mybatis
  global-config:
    db-config:
      id-type: auto
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  extend:
    include-tables: t_file




security:
  oauth2:
    client:
      client-secret: client
      client-id: client
      scope: server
      grant-type: client_credentials,password
      access-token-uri: http://wemirr-platform-authority/oauth/token
      ignore:
        resource-urls:
          - /oauth/**
          - /swagger-resources
          - /swagger-resources/**
          - /v2/api-docs
          - /v3/api-docs
          - /swagger-ui/**
          - /v3/api-docs/**
          - /swagger-ui.html
          - /swagger-ui/index.html
          - /favicon.ico
          - /station_messages/**
    resource:
      # 这个地方如果不是同一个注册容器，则不用开启
      loadBalanced: true
      token-info-uri: http://wemirr-platform-authority/oauth/check_token
      prefer-token-info: false
      user-info-uri: http://wemirr-platform-authority/oauth/users
extend:
  oss:
    cloud:
      qiniu:
        enabled: true
        #access-key: 写自己的
        #secret-key: 写自己的
        region: region0
        bucket: battcn
        mapping-path: http://qiniu.battcn.com
