spring:
  application:
    name: battcn-demo-provider
server:
  port: 9090
management:
  port: 9091
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
dubbo:
  scan:
    base-packages: com.battcn.demo.provider.service
  application:
    id: battcn-demo-provider
    name: battcn-demo-provider
    qos-port: 22222
    qos-enable: true
  registry:
    address: N/A
    id: my-registry
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
    status: server
endpoints:
  dubbo:
    enabled: true

