server:
  port: 8082
spring:
  application:
    name: battcn-management-consumer
  swagger:
    base-package: com.battcn
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/  
    suffix: .html

management:
  port: 8083
  health:
    db:
      enabled: false
    dubbo:
      status:
        defaults: memory
dubbo:
  application:
    id: battcn-management-consumer
    name: battcn-management-consumer
    qos-port: 22223
endpoints:
  dubbo:
    enabled: true
  