spring:
  application:
    name: battcn-demo-consumer
server:
  port: 8080
management:
  port: 8081
  health:
    dubbo:
      status:
        defaults: memory
dubbo:
  application:
    id: battcn-demo-consumer
    name: battcn-demo-consumer
    qos-port: 22223
endpoints:
  dubbo:
    enabled: true

